#!/bin/bash
# RULER Evaluation — DuoAttention
# Sweeps sparsity values by rewriting baselines/duo_attn/config.py.
#
# DuoAttention requires a dedicated conda env with transformers==4.45.2,
# flash-attn==2.6.3, and `pip install -e /home/yoongonkim/duo-attention/`.
# Set DUO_ENV_NAME (default: duo_env) and CONDA_SETUP to override.
set -e

# ---- Conda activation ----
DUO_ENV_NAME="${DUO_ENV_NAME:-duo_env}"
CONDA_SETUP="${CONDA_SETUP:-$HOME/miniconda3/etc/profile.d/conda.sh}"
if [[ -f "$CONDA_SETUP" ]]; then
    # shellcheck disable=SC1090
    source "$CONDA_SETUP"
    conda activate "$DUO_ENV_NAME"
else
    echo "WARNING: $CONDA_SETUP not found; assuming duo_env is already active."
fi

# ---- Configuration (env defaults, overridable via CLI flags below) ----
BASE_MODEL="${BASE_MODEL:-meta-llama/Llama-3.1-8B-Instruct}"
NUM_SAMPLES="${NUM_SAMPLES:-25}"
PREPARE_FLAG=""

# ---- Parse CLI flags ----
usage() {
    echo "Usage: $0 [--base_model MODEL] [--num_samples N] [--prepare]"
}
while [[ $# -gt 0 ]]; do
    case "$1" in
        --base_model)   BASE_MODEL="$2"; shift 2 ;;
        --num_samples)  NUM_SAMPLES="$2"; shift 2 ;;
        --prepare)      PREPARE_FLAG="--prepare"; shift ;;
        -h|--help)      usage; exit 0 ;;
        *)              echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

# DuoAttention only has patterns for Llama. Hard-fail otherwise.
case "$(echo "$BASE_MODEL" | tr '[:upper:]' '[:lower:]')" in
    *llama*)  MODEL_TAG="llama" ;;
    *) echo "DuoAttention baseline supports Llama only (got: $BASE_MODEL)"; exit 1 ;;
esac

OUTPUT_DIR="${OUTPUT_DIR:-results_ruler/duo_attention/${MODEL_TAG}}"

# Sequence lengths to evaluate
SEQ_LENGTHS="${SEQ_LENGTHS:-32768}"

# Pattern location (upstream DuoAttention repo)
PATTERN_ROOT="${PATTERN_ROOT:-/home/yoongonkim/duo-attention/attn_patterns}"
PATTERN_SUBDIR="${PATTERN_SUBDIR:-Meta-Llama-3.1-8B-Instruct/lr=0.02-reg=0.05-ctx=1000_128000-multi_passkey10}"

SINK_SIZE=64
RECENT_SIZE=256

CONFIG_FILE="baselines/duo_attn/config.py"

write_config() {
    local sparsity="$1"
    local sink="$2"
    local recent="$3"
    cat > "$CONFIG_FILE" <<PYEOF
"""
DuoAttention evaluation configuration (auto-generated by run_ruler_duo.sh).
"""

DUO_ATTN_CONFIG = {
    "base_model": "${BASE_MODEL}",
    "pattern_root": "${PATTERN_ROOT}",
    "pattern_subdir": "${PATTERN_SUBDIR}",
    "sparsity": ${sparsity},
    "sink_size": ${sink},
    "recent_size": ${recent},
}
PYEOF
}

# ---- Sweep sparsity ----
for SPARSITY in 0.25 0.5 0.75; do
    RUN_NAME="${MODEL_TAG}_duo_sp${SPARSITY}_sink${SINK_SIZE}_recent${RECENT_SIZE}"

    echo ""
    echo "===================================================================="
    echo "DUO: sparsity=${SPARSITY}, sink=${SINK_SIZE}, recent=${RECENT_SIZE}"
    echo "===================================================================="

    write_config "$SPARSITY" "$SINK_SIZE" "$RECENT_SIZE"

    python eval_ruler.py \
        --mode duo_attention \
        --base_model "$BASE_MODEL" \
        --skip_existing \
        $PREPARE_FLAG \
        --seq_lengths $SEQ_LENGTHS \
        --num_samples "$NUM_SAMPLES" \
        --output_dir "$OUTPUT_DIR" \
        --run_name "$RUN_NAME"
done

echo ""
echo "============================================================"
echo "ALL RUNS COMPLETE. Results in: $OUTPUT_DIR/"
echo "============================================================"
