#!/bin/bash
# LongBench v2 Evaluation — InfLLM
# Sweeps InfLLM's main sparsity knobs (topk / block_size / n_local) by
# rewriting baselines/inf_llm/config.py.
#
# InfLLM requires a dedicated conda env with transformers==4.37.2. Set
# INFLLM_ENV_NAME (default: inf_llm_env) and CONDA_SETUP to override.
set -e

# ---- Conda activation ----
INFLLM_ENV_NAME="${INFLLM_ENV_NAME:-infllm}"
CONDA_SETUP="${CONDA_SETUP:-/home/tools/anaconda3/etc/profile.d/conda.sh}"
if [[ -f "$CONDA_SETUP" ]]; then
    # shellcheck disable=SC1090
    source "$CONDA_SETUP"
    conda activate "$INFLLM_ENV_NAME"
else
    echo "WARNING: $CONDA_SETUP not found; assuming $INFLLM_ENV_NAME is already active."
fi

# ---- Configuration ----
BASE_MODEL="${BASE_MODEL:-meta-llama/Llama-3.1-8B-Instruct}"
MODEL_FAMILY="${MODEL_FAMILY:-llama3}"
MAX_INPUT_LEN="${MAX_INPUT_LEN:-127500}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-128}"
NUM_SAMPLES="${NUM_SAMPLES:--1}"
PREFILL_CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-2048}"
OUTPUT_DIR="${OUTPUT_DIR:-results/results_longbench_v2/inf_llm}"

# Llama only (InfLLM upstream + this repo)
case "$(echo "$BASE_MODEL" | tr '[:upper:]' '[:lower:]')" in
    *llama*)  ;;
    *) echo "InfLLM baseline supports Llama only (got: $BASE_MODEL)"; exit 1 ;;
esac

# Fixed InfLLM parameters (CLI-exposed; passed through per-run).
# REPR_TOPK is swept below (representative tokens per block, quality knob).
# MAX_CACHED_BLOCK is derived from TOPK inside the sweep (must be >= topk;
# upstream uses 2*topk). Raising it only costs GPU memory, not quality.
N_INIT=128
CHUNK_SIZE=8192

# Fixed config-only parameters that are not being swept.
ATTN_TYPE="inf-llm"
EXC_BLOCK_SIZE=512

CONFIG_FILE="baselines/infllm/config.py"

write_config() {
    local block_size="$1"
    local n_local="$2"
    local topk="$3"
    local repr_topk="$4"
    cat > "$CONFIG_FILE" <<PYEOF
"""
InfLLM evaluation configuration (auto-generated by run_longbench_v2_infllm.sh).

Requires transformers==4.37.2. Llama 3.x only.
"""

INF_LLM_CONFIG = {
    "base_model": "${BASE_MODEL}",
    "attn_type": "${ATTN_TYPE}",
    "block_size": ${block_size},
    "n_init": ${N_INIT},
    "n_local": ${n_local},
    "topk": ${topk},
    "repr_topk": ${repr_topk},
    "max_cached_block": ${MAX_CACHED_BLOCK},
    "exc_block_size": ${EXC_BLOCK_SIZE},
    "fattn": False,
    "base": None,
    "distance_scale": 1.0,
    "score_decay": None,
    "async_global_stream": False,
    "faiss": False,
    "perhead": False,
    "chunk_size": ${CHUNK_SIZE},
}
PYEOF
}

# ---- Sweep block_size x n_local x topk x repr_topk ----
for BLOCK_SIZE in 128; do
    for N_LOCAL in 4096; do
        for TOPK in 8 16 32; do
            for REPR_TOPK in 4; do
                MAX_CACHED_BLOCK=$(( TOPK * 2 ))
                RUN_NAME="${MODEL_FAMILY}_inf_llm_bs${BLOCK_SIZE}_nlocal${N_LOCAL}_topk${TOPK}_nini${N_INIT}_repr${REPR_TOPK}"

                echo ""
                echo "===================================================================="
                echo "INFLLM: block_size=${BLOCK_SIZE}, n_local=${N_LOCAL}, topk=${TOPK}, repr_topk=${REPR_TOPK}"
                echo "===================================================================="

                write_config "$BLOCK_SIZE" "$N_LOCAL" "$TOPK" "$REPR_TOPK"

                python eval_longbench_v2.py \
                    --mode inf_llm \
                    --base_model "$BASE_MODEL" \
                    --max_input_len "$MAX_INPUT_LEN" \
                    --max_new_tokens "$MAX_NEW_TOKENS" \
                    --num_samples "$NUM_SAMPLES" \
                    --prefill_chunk_size "$PREFILL_CHUNK_SIZE" \
                    --inf_llm_n_init "$N_INIT" \
                    --inf_llm_repr_topk "$REPR_TOPK" \
                    --inf_llm_max_cached_block "$MAX_CACHED_BLOCK" \
                    --inf_llm_chunk_size "$CHUNK_SIZE" \
                    --output_dir "$OUTPUT_DIR" \
                    --run_name "$RUN_NAME"
            done
        done
    done
done

# ---- Summarize all results ----
echo ""
echo "============================================================"
echo "SUMMARIZING ALL RESULTS"
echo "============================================================"
python3 summarize_longbench_v2.py "$OUTPUT_DIR"
