#!/bin/bash
# LongBench v2 Evaluation — DuoAttention
# Sweeps sparsity values by rewriting baselines/duo_attn_baseline/config.py.
set -e

# ---- Conda activation ----
DUO_ENV_NAME="${DUO_ENV_NAME:-duo_env}"
CONDA_SETUP="${CONDA_SETUP:-$HOME/miniconda3/etc/profile.d/conda.sh}"
if [[ -f "$CONDA_SETUP" ]]; then
    # shellcheck disable=SC1090
    source "$CONDA_SETUP"
    conda activate "$DUO_ENV_NAME"
else
    echo "WARNING: $CONDA_SETUP not found; assuming duo_env is already active."
fi

# ---- Configuration ----
BASE_MODEL="${BASE_MODEL:-meta-llama/Llama-3.1-8B-Instruct}"
MODEL_FAMILY="${MODEL_FAMILY:-llama3}"
MAX_INPUT_LEN="${MAX_INPUT_LEN:-127500}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-128}"
NUM_SAMPLES="${NUM_SAMPLES:--1}"
PREFILL_CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-2048}"
OUTPUT_DIR="${OUTPUT_DIR:-results/results_longbench_v2/duo_attention}"

# Llama only
case "$(echo "$BASE_MODEL" | tr '[:upper:]' '[:lower:]')" in
    *llama*)  ;;
    *) echo "DuoAttention baseline supports Llama only (got: $BASE_MODEL)"; exit 1 ;;
esac

# Pattern location (upstream DuoAttention repo)
PATTERN_ROOT="${PATTERN_ROOT:-/home/yoongonkim/duo-attention/attn_patterns}"
PATTERN_SUBDIR="${PATTERN_SUBDIR:-Meta-Llama-3.1-8B-Instruct/lr=0.02-reg=0.05-ctx=1000_128000-multi_passkey10}"

SINK_SIZE=64
RECENT_SIZE=256

CONFIG_FILE="baselines/duo_attn_baseline/config.py"

write_config() {
    local sparsity="$1"
    local sink="$2"
    local recent="$3"
    cat > "$CONFIG_FILE" <<PYEOF
"""
DuoAttention evaluation configuration (auto-generated by run_longbench_v2_duo.sh).
"""

DUO_ATTN_CONFIG = {
    "base_model": "${BASE_MODEL}",
    "pattern_root": "${PATTERN_ROOT}",
    "pattern_subdir": "${PATTERN_SUBDIR}",
    "sparsity": ${sparsity},
    "sink_size": ${sink},
    "recent_size": ${recent},
}
PYEOF
}

# ---- Sweep sparsity ----
for SPARSITY in 0.25 0.5 0.75; do
    RUN_NAME="${MODEL_FAMILY}_duo_sp${SPARSITY}_sink${SINK_SIZE}_recent${RECENT_SIZE}"

    echo ""
    echo "===================================================================="
    echo "DUO: sparsity=${SPARSITY}, sink=${SINK_SIZE}, recent=${RECENT_SIZE}"
    echo "===================================================================="

    write_config "$SPARSITY" "$SINK_SIZE" "$RECENT_SIZE"

    python eval_longbench_v2.py \
        --mode duo_attention \
        --base_model "$BASE_MODEL" \
        --max_input_len "$MAX_INPUT_LEN" \
        --max_new_tokens "$MAX_NEW_TOKENS" \
        --num_samples "$NUM_SAMPLES" \
        --prefill_chunk_size "$PREFILL_CHUNK_SIZE" \
        --output_dir "$OUTPUT_DIR" \
        --run_name "$RUN_NAME"
done

# ---- Summarize all results ----
echo ""
echo "============================================================"
echo "SUMMARIZING ALL RESULTS"
echo "============================================================"
python3 summarize_longbench_v2.py "$OUTPUT_DIR"
