#!/bin/bash
# RULER Evaluation — InfLLM
# Sweeps InfLLM's main sparsity knobs (topk / block_size / n_local) by
# rewriting baselines/inf_llm/config.py. Only topk/block_size/n_local are
# config-only in eval_ruler.py; n_init / repr_topk / max_cached_block /
# chunk_size are passed as CLI args.
#
# InfLLM requires a dedicated conda env with transformers==4.37.2 (its
# patch.py targets pre-4.45 attention internals). Set INFLLM_ENV_NAME
# (default: inf_llm_env) and CONDA_SETUP to override.
set -e

# ---- Conda activation ----
INFLLM_ENV_NAME="${INFLLM_ENV_NAME:-inf_llm_env}"
CONDA_SETUP="${CONDA_SETUP:-$HOME/miniconda3/etc/profile.d/conda.sh}"
if [[ -f "$CONDA_SETUP" ]]; then
    # shellcheck disable=SC1090
    source "$CONDA_SETUP"
    conda activate "$INFLLM_ENV_NAME"
else
    echo "WARNING: $CONDA_SETUP not found; assuming $INFLLM_ENV_NAME is already active."
fi

# ---- Configuration (env defaults, overridable via CLI flags below) ----
BASE_MODEL="${BASE_MODEL:-meta-llama/Llama-3.1-8B-Instruct}"
NUM_SAMPLES="${NUM_SAMPLES:-25}"
PREPARE_FLAG=""

# ---- Parse CLI flags ----
usage() {
    echo "Usage: $0 [--base_model MODEL] [--num_samples N] [--prepare]"
}
while [[ $# -gt 0 ]]; do
    case "$1" in
        --base_model)   BASE_MODEL="$2"; shift 2 ;;
        --num_samples)  NUM_SAMPLES="$2"; shift 2 ;;
        --prepare)      PREPARE_FLAG="--prepare"; shift ;;
        -h|--help)      usage; exit 0 ;;
        *)              echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

# InfLLM upstream only supports Llama 3.x here. Hard-fail otherwise.
case "$(echo "$BASE_MODEL" | tr '[:upper:]' '[:lower:]')" in
    *llama*)  MODEL_TAG="llama" ;;
    *) echo "InfLLM baseline supports Llama only (got: $BASE_MODEL)"; exit 1 ;;
esac

OUTPUT_DIR="${OUTPUT_DIR:-results_ruler/inf_llm/${MODEL_TAG}}"

# Sequence lengths to evaluate
SEQ_LENGTHS="${SEQ_LENGTHS:-32768}"

# Fixed InfLLM parameters (CLI-exposed; passed through per-run).
# REPR_TOPK is swept below (representative tokens per block, quality knob).
# MAX_CACHED_BLOCK is derived from TOPK inside the sweep (must be >= topk;
# upstream uses 2*topk). Raising it only costs GPU memory, not quality.
N_INIT=4
CHUNK_SIZE=8192

# Fixed config-only parameters that are not being swept.
ATTN_TYPE="inf-llm"
EXC_BLOCK_SIZE=512

CONFIG_FILE="baselines/infllm/config.py"

write_config() {
    local block_size="$1"
    local n_local="$2"
    local topk="$3"
    local repr_topk="$4"
    cat > "$CONFIG_FILE" <<PYEOF
"""
InfLLM evaluation configuration (auto-generated by run_ruler_infllm.sh).

Requires transformers==4.37.2; see baselines/inf_llm/config.py history for
env setup notes. Llama 3.x only.
"""

INF_LLM_CONFIG = {
    # Base model (HF Hub ID or local path). Llama 3.x only.
    "base_model": "${BASE_MODEL}",

    # Which attention variant from inf_llm.attention.ATTN_FORWRAD to use.
    "attn_type": "${ATTN_TYPE}",

    # Memory/block parameters (swept by run_ruler_infllm.sh).
    "block_size": ${block_size},
    "n_init": ${N_INIT},
    "n_local": ${n_local},
    "topk": ${topk},
    "repr_topk": ${repr_topk},
    "max_cached_block": ${MAX_CACHED_BLOCK},
    "exc_block_size": ${EXC_BLOCK_SIZE},

    # Triton flash attention (requires nightly triton; leave False by default).
    "fattn": False,

    # RoPE. None => inherit from model's rotary_emb.base.
    "base": None,
    "distance_scale": 1.0,

    # Advanced knobs (upstream defaults).
    "score_decay": None,
    "async_global_stream": False,
    "faiss": False,
    "perhead": False,

    # GreedySearch prefill chunk size.
    "chunk_size": ${CHUNK_SIZE},
}
PYEOF
}

# ---- Sweep block_size x n_local x topk x repr_topk ----
# block_size * topk = attended-block token budget; n_local is the sliding window.
# repr_topk = # of representative tokens per block (block-summary fidelity).
for BLOCK_SIZE in 16; do
    for N_LOCAL in 4096; do
        for TOPK in 128 64; do
            for REPR_TOPK in 1 2; do
                MAX_CACHED_BLOCK=$(( TOPK * 2 ))
                RUN_NAME="${MODEL_TAG}_inf_llm_bs${BLOCK_SIZE}_nlocal${N_LOCAL}_topk${TOPK}_nini${N_INIT}_repr${REPR_TOPK}"

                echo ""
                echo "===================================================================="
                echo "INFLLM: block_size=${BLOCK_SIZE}, n_local=${N_LOCAL}, topk=${TOPK}, repr_topk=${REPR_TOPK}"
                echo "===================================================================="

                write_config "$BLOCK_SIZE" "$N_LOCAL" "$TOPK" "$REPR_TOPK"

                python eval_ruler.py \
                    --mode inf_llm \
                    --base_model "$BASE_MODEL" \
                    --skip_existing \
                    $PREPARE_FLAG \
                    --seq_lengths $SEQ_LENGTHS \
                    --num_samples "$NUM_SAMPLES" \
                    --inf_llm_n_init "$N_INIT" \
                    --inf_llm_repr_topk "$REPR_TOPK" \
                    --inf_llm_max_cached_block "$MAX_CACHED_BLOCK" \
                    --inf_llm_chunk_size "$CHUNK_SIZE" \
                    --output_dir "$OUTPUT_DIR" \
                    --run_name "$RUN_NAME"
            done
        done
    done
done

echo ""
echo "============================================================"
echo "ALL RUNS COMPLETE. Results in: $OUTPUT_DIR/"
echo "============================================================"
