"""
InfLLM evaluation configuration (auto-generated by run_ruler_infllm.sh).

Targets transformers 5.2.0 in the DCT_Page conda env. Llama 3.x only.
"""

INF_LLM_CONFIG = {
    # Base model (HF Hub ID or local path). Llama 3.x only.
    "base_model": "meta-llama/Llama-3.1-8B-Instruct",

    # Which attention variant from inf_llm.attention.ATTN_FORWRAD to use.
    "attn_type": "inf-llm",

    # Memory/block parameters (swept by run_ruler_infllm.sh).
    "block_size": 16,
    "n_init": 128,
    "n_local": 4096,
    # Output sliding window; None => uses n_local. Must be <= n_local.
    # Decouples the local-output window from the block-scoring horizon.
    "n_recent": None,
    "topk": 128,
    "repr_topk": 4,
    "max_cached_block": 256,
    "exc_block_size": 512,

    # Triton flash attention (requires nightly triton; leave False by default).
    "fattn": False,

    # RoPE. None => inherit from model's rotary_emb.base.
    "base": None,
    "distance_scale": 1.0,

    # Advanced knobs (upstream defaults).
    "score_decay": None,
    "async_global_stream": False,
    "faiss": False,
    "perhead": False,

    # GreedySearch prefill chunk size.
    "chunk_size": 8192,
}
