"""
InfLLM evaluation configuration (auto-generated by run_ruler_infllm.sh).

Requires transformers==4.37.2; see baselines/inf_llm/config.py history for
env setup notes. Llama 3.x only.
"""

INF_LLM_CONFIG = {
    # Base model (HF Hub ID or local path). Llama 3.x only.
    "base_model": "meta-llama/Llama-3.1-8B-Instruct",

    # Which attention variant from inf_llm.attention.ATTN_FORWRAD to use.
    "attn_type": "inf-llm",

    # Memory/block parameters (swept by run_ruler_infllm.sh).
    "block_size": 16,
    "n_init": 4,
    "n_local": 4096,
    "topk": 64,
    "repr_topk": 2,
    "max_cached_block": 128,
    "exc_block_size": 512,

    # Triton flash attention (requires nightly triton; leave False by default).
    "fattn": False,

    # RoPE. None => inherit from model's rotary_emb.base.
    "base": None,
    "distance_scale": 1.0,

    # Advanced knobs (upstream defaults).
    "score_decay": None,
    "async_global_stream": False,
    "faiss": False,
    "perhead": False,

    # GreedySearch prefill chunk size.
    "chunk_size": 8192,
}
